---
title: "World Happiness Report 2020"
author:
- familyname: Luo
  othernames: Yu
  address: Monash University
  email: yluo0065@student.monash.com
  correspondingauthor: true
  qualifications:  Master
- familyname: Thakker
  othernames: Khushee
  address: Monash University
  email: ktha0021@student.monash.edu
  qualifications: Master
- familyname: Chen
  othernames: Yunqi
  address: Monash University
  email: yche0454@student.monash.edu
  correspondingauthor: true
  qualifications:  Master
organization: the World Bank data base
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message=FALSE, 
                      warning=FALSE,
                      fig.width = 6, 
                      fig.height = 4,
                      fig.align="center")
knitr::opts_chunk$set(fig.pos = "!h", out.extra = "")

# Libraries

library(tidyverse)
library(readxl)
library(kableExtra)
library(bookdown)
library(ggplot2)
library(stringr)
library(lubridate)
```


```{r read-data}
# Read the data
WHR20 <- read_excel("Data/WHR20_DataForFigure2.1.xls")
```

\section*{Introduction}

\section*{1 }

\subsection*{1.2 }


\clearpage
\section*{2 }

\subsection*{2.1 GDP}

```{r GDP-ord}
gdp_mean <- WHR20 %>% 
  group_by(`Regional indicator`) %>% 
  summarise(Average 
            = round(mean(`Logged GDP per capita`),2))%>%
  arrange(-Average)

  gdp_mean %>% kable() %>%
      kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r GDP-dens, eval = FALSE}
ggplot(WHR20, aes(x = `Logged GDP per capita`))+
  geom_density()+
  geom_vline(aes(xintercept =
                   mean(`Logged GDP per capita`)),
             linetype = "dashed")

mean(WHR20$`Logged GDP per capita`)

quantile(WHR20$`Logged GDP per capita`)
```

```{r GDP-high}
 WHR20 %>%
  filter(`Regional indicator` != 
           c("Commonwealth of Independent States",
             "South Asia", 
             "Sub-Saharan Africa")) %>% 
  ggplot(aes(x = `Ladder score`, 
             y = `Logged GDP per capita`)) +
  geom_point() +
  facet_wrap(~`Regional indicator`, ncol = 3)
```

```{r GDP-high}
 WHR20 %>%
  filter(`Regional indicator` %in% 
           c("Commonwealth of Independent States",
             "South Asia", 
             "Sub-Saharan Africa")) %>% 
  ggplot(aes(x = `Ladder score`, 
             y = `Freedom to make life choices`)) +
  geom_point() +
  facet_wrap(~`Regional indicator`, ncol = 3)
```

\subsection*{2.2 Social support}

```{r SS-ord}
SS_mean <- WHR20 %>% 
  group_by(`Regional indicator`) %>% 
  summarise(Average 
            = round(mean(`Social support`),2))%>%
  arrange(-Average)

  SS_mean %>% kable() %>% 
      kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r SS-dens, eval = FALSE}
ggplot(WHR20, aes(x = `Social support`))+
  geom_density()+
  geom_vline(aes(xintercept =
                   mean(`Social support`)),
             linetype = "dashed")

mean(WHR20$`Social support`)

quantile(WHR20$`Social support`)
```

```{r SS-high}
 WHR20 %>%
  filter(`Regional indicator` != 
           c("Middle East and North Africa",
             "South Asia", 
             "Sub-Saharan Africa")) %>% 
  ggplot(aes(x = `Ladder score`, 
             y = `Social support`)) +
  geom_point() +
  facet_wrap(~`Regional indicator`, ncol = 3)
```

```{r SS-high}
 WHR20 %>%
  filter(`Regional indicator` %in% 
           c("Middle East and North Africa",
             "South Asia", 
             "Sub-Saharan Africa")) %>% 
  ggplot(aes(x = `Ladder score`, 
             y = `Social support`)) +
  geom_point() +
  facet_wrap(~`Regional indicator`, ncol = 3)
```

\subsection*{2.3 Social Healthy life expectancy}

```{r HLE-ord}
HLE_mean <- WHR20 %>% 
  group_by(`Regional indicator`) %>% 
  summarise(Average 
            = round(mean(`Healthy life expectancy`),2))%>%
  arrange(-Average)

  HLE_mean %>% kable() %>% 
      kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r HLE-dens, eval = FALSE}
ggplot(WHR20, aes(x = `Healthy life expectancy`))+
  geom_density()+
  geom_vline(aes(xintercept =
                   mean(`Healthy life expectancy`)),
             linetype = "dashed")

mean(WHR20$`Healthy life expectancy`)

quantile(WHR20$`Healthy life expectancy`)
```

```{r SS-high}
 WHR20 %>%
  filter(`Regional indicator` != 
           c("South Asia", 
             "Sub-Saharan Africa")) %>% 
  ggplot(aes(x = `Ladder score`, 
             y = `Social support`)) +
  geom_point() +
  facet_wrap(~`Regional indicator`, ncol = 3)
```

```{r SS-high}
 WHR20 %>%
  filter(`Regional indicator` %in% 
           c("South Asia", 
             "Sub-Saharan Africa")) %>% 
  ggplot(aes(x = `Ladder score`, 
             y = `Social support`)) +
  geom_point() +
  facet_wrap(~`Regional indicator`, ncol = 3)
```

\clearpage
\section*{3 }

\subsection*{3.1 }

\clearpage
\section*{Conclusion}

\clearpage
\section*{References}


